<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "joboffers"
 *
 * Auto generated by Extension Builder 2017-07-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Job Offers',
    'description' => 'Organization of Job Offers.',
    'category' => 'plugin',
    'author' => 'Torben Aschmons',
    'author_email' => 't3dev-YYYY@aschmons.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
